[project]
name = "f1news"
version = "0.1.0"
description = "Honza Javorek's personal F1 news feed"
readme = "README.md"
authors = [{name = "Honza Javorek", email = "mail@honzajavorek.cz"}]
license = {text = "AGPL-3.0-only"}
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.2,<9.0.0",
    "lxml>=6.0.4,<7.0.0",
    "praw>=7.8.1,<9.0.0",
    "stamina>=25.2,<27.0",
]

[project.scripts]
f1news = "f1news.__main__:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.13.0"]
build-backend = "uv_build"
